version: "3.7"
services:
  zuvy_production:
    build:
      context: .
      dockerfile: Dockerfile
    image : zuvy_production
    container_name: zuvy_container_production
    # depends_on:
    # - db
    # - redis
    ports:
      - "4777:5000"
    env_file:
      - .env
