export enum NotificationType {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  RESCHEDULE_REQUEST = 'RESCHEDULE_REQUEST',
  RESCHEDULE_ACCEPTED = 'RESCHEDULE_ACCEPTED',
  RESCHEDULE_DECLINED = 'RESCHEDULE_DECLINED',
  SESSION_REMINDER = 'SESSION_REMINDER',
}
